project_name: "HonkaiImpact3-OneDragon"
python_version: "3.11"
github_homepage: "https://github.com/pared2021/HonkaiImpact3-OneDragon"
github_https_repository: "https://github.com/pared2021/HonkaiImpact3-OneDragon.git"
github_ssh_repository: "git@github.com:pared2021/HonkaiImpact3-OneDragon.git"
gitee_https_repository: ""
gitee_ssh_repository: ""
project_git_branch: "main"
game_executable_name: "BH3.exe"
screen_standard_width: 1920
screen_standard_height: 1080
notice_url: ""
qq_link: ""
quick_start_link: ""
home_page_link: ""
doc_link: ""
